### ISSUE TITLE
calendar event tab (color based on grade)

### ISSUE THREAD

**Issue by vvwenv** [sitechtimes/course-selection-frontend-v2#138]

**Comment by bridgetf7** [comment]
**Freshman meet**
bg-[#F5CDCD] text-[#590000] 
**Sophomore meet**
bg-[#D2F6D2] text-[#003400]
**Junior meet**
bg-[#EED7FD] text-[#2D004B]
**Senior meet**
 bg-[#CCDDF5] text-[#002254]
