### ISSUE TITLE
router/watch functions comparing survey responses 

### ISSUE THREAD

**Issue by bridgetf7** [sitechtimes/course-selection-frontend-v2#248]
Functions that compare `JSON.stringify(surveyStore.currentResponse) === surveyStore.currentAnsweredSurvey.answers` are not working as intended, as they are not in the same data structure but are intended to provided the same information

**Comment by whydoesthecodenotwork** [comment]
![image](https://github.com/sitechtimes/course-selection-frontend-v2/assets/91681777/0ef969fb-8c3b-4cd7-8a18-e683661d0a57)
tldr; surveyStore.currentAnsweredSurvey.answers is written to Once when `fetchSurvey()` is called, then never again. this makes it awful for checking if the user has saved

update: [latest commit](https://github.com/sitechtimes/course-selection-frontend-v2/pull/268/commits/c7ffe08c8dfae9036f5cb9a5f5cece3c74deb825) should fix this
