### ISSUE TITLE
missing answers 

### ISSUE THREAD

**Issue by bridgetf7** [sitechtimes/course-selection-frontend-v2#270]
show red highlight that denotes an answer is missing on reviewSurvey page

**Comment by whydoesthecodenotwork** [comment]
i thought the red highlights for missing answers were already a thing
![red highlight on /student/survey/review](https://github.com/sitechtimes/course-selection-frontend-v2/assets/91681777/b982633d-031f-4cf3-ac5b-a9029c3bca34)
