### ISSUE TITLE
can't choose 0 ap courses

### ISSUE THREAD

**Issue by whydoesthecodenotwork** [sitechtimes/course-selection-frontend-v2#281]
dropdown lacks option for a student to choose 0 ap courses
official naviance survey has this option so i assume it's possible

**Comment by bridgetf7** [comment]
I believe there's a minimum to the number of AP courses a student takes in a year.
Freshmen/Sophomore: 1 (APWH)
Junior: 1 (APUSH)
Senior: 1 (AP Macro or AP Gov)

**Comment by whydoesthecodenotwork** [comment]
there's a non-ap social studies class as well

from naviance:
- SOCIAL STUDIES - AP Macroeconomics (Rank 1 to 3 or Not Interested)
- SOCIAL STUDIES - AP US Government &amp; Politics (Rank 1 to 3 or Not Interested)
- SOCIAL STUDIES - NON - AP Government /Economics - High School Credit ONLY - You must select this as a choice for Social Studies (Rank 1 to 3)

**Comment by bridgetf7** [comment]
oh my bad I forgot about that

thank you
